### ISSUE TITLE
Feature Request: Any system & user driven dark/light theme support using next-themes library

### ISSUE THREAD

**Issue by avibathula** [ixartz/SaaS-Boilerplate#40] opened 2024-09-17 05:44 UTC
https://dev.to/sujit-shrc/implementing-dark-and-light-themes-in-nextjs-13-with-tailwind-css-57l5

**Comment by ixartz** [comment] 2024-09-17 11:07
Duplicate of https://github.com/ixartz/SaaS-Boilerplate/issues/29

**Closed by ixartz** 2024-09-17 11:07 UTC

**Comment by ixartz** [comment] 2024-10-15 17:25
Just implemented and released a dark mode, there is a live demo at: https://pro-demo.nextjs-boilerplate.com
